name: Release Obsidian plugin

on:
  workflow_dispatch: 
#  push:
#    tags:
#      - '*'

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: 
            main.js
            manifest.json
            styles.css
